source 'http://rubygems.org'

gem 'rails'

gem 'sqlite3'

gem 'sass-rails'
gem 'coffee-rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', :platform => :ruby

gem 'uglifier'
gem 'summernote-rails', :path => '../'
gem 'font-awesome-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'bootstrap-sass'